version: "3.7"

services:

  hmac_server:
    build:
      context: ./hmac_server
    command: python hmac_generator/manage.py runserver 0:8080
    container_name: hmac_server
    env_file: ./hmac_server/.env
    ports:
      - "8080:8080"
    volumes:
      - ./hmac_server:/usr/src/app/hmac_server

volumes:
  hmac-database:
